services:
  - type: web
    name: wss-ip-server
    runtime: node
    env: production
    plan: free  
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
